#!/bin/bash
set -e

VERSION="1.9.5"
OS="linux"

function detectOS() {
    case "$(uname -s)" in
        Darwin)
            OS="darwin"
            echo "++ Detected MacOS"
            ;;
        Linux)
            OS="linux"
            echo "++ Detected Linux"
            ;;
        CYGWIN*|MINGW32*|MSYS*)
            echo "We don't support Windows"
            exit 2
            ;;
    esac
}


function postInstall() {
    # post install some go tools
    export GOROOT="$HOME/go"
    export GOPATH="$HOME/gos"
    export PATH="$GOROOT/bin:$GOPATH/bin:$PATH"

    echo 'Installing gotags...'
    go get -u github.com/jstemmer/gotags

    echo 'Installing godef...'
    go get -u github.com/rogpeppe/godef

    echo 'Installing govendor...'
    go get -u github.com/kardianos/govendor

    echo "Installing delve..."
    go get -u github.com/derekparker/delve/cmd/dlv

    echo "Installing dep..."
    go get -u github.com/golang/dep/cmd/dep
}

function alreadyInstalled() {
    if [ -e ~/go ]; then
        echo 'golang already installed. exit'
        exit 1
    fi
}

function downloadAndInstallGo() {
    URL="https://mirrors.ustc.edu.cn/golang/go${VERSION}.${OS}-amd64.tar.gz"
    GO=`basename $URL`
    chkfile='sha256.txt'

    wget $URL --no-check-certificate -O $GO
    echo $GO

    wget "${URL}.sha256" -O $chkfile

    echo 'Checking sha256'
    echo "`cat $chkfile`  $GO" |  sha256sum --check -
    rm $chkfile

    tar xzf $GO
    mv -v go ~/
    mkdir ~/gos
    rm $GO
}

detectOS
alreadyInstalled
downloadAndInstallGo
postInstall

# All is ok
echo 'Go install finished..'
echo 'Please copy bashrc into $HOME dir to make go work'

