#!/bin/bash
set -e

if [ -e ~/go ]; then
    echo 'golang already installed. exit'
    exit 1
fi

url="https://mirrors.ustc.edu.cn/golang/go1.9.2.linux-amd64.tar.gz"
GO=`basename $url`
wget $url --no-check-certificate -O $GO
echo $GO

echo 'Check sha256'
echo "de874549d9a8d8d8062be05808509c09a88a248e77ec14eb77453530829ac02b  $GO" |  sha256sum --check -

tar xzf $GO
mv -v go ~/
mkdir ~/gos

echo 'Go install finished..'
echo 'Please copy bashrc into $HOME dir to make go work'
echo 'run: go get -u github.com/jstemmer/gotags to install gotags.'
echo 'run: go get -u github.com/rogpeppe/godef to install godef'

rm $GO
