#!/bin/bash
set -e

if [ -e ~/go ]; then
    echo 'golang already installed. exit'
    exit 1
fi

url="https://mirrors.ustc.edu.cn/golang/go1.9.1.linux-amd64.tar.gz"
wget $url --no-check-certificate
GO=`basename $url`
echo $GO

echo 'Check sha256'
echo "07d81c6b6b4c2dcf1b5ef7c27aaebd3691cdb40548500941f92b221147c5d9c7  $GO" |  sha256sum --check -

tar xzf $GO
mv -v go ~/
mkdir ~/gos

echo 'Go install finished..'
echo 'Please copy bashrc into $HOME dir to make go work'
echo 'run: go get -u github.com/jstemmer/gotags to install gotags.'
echo 'run: go get -u github.com/rogpeppe/godef to install godef'

rm $GO
